### ISSUE TITLE
online vs. Buchzitate: welche Listen brauchen wir?

### ISSUE THREAD

**Issue by simar0at** [acdh-oeaw/wboe-redaktionstool#153]
In GitLab by @andreas.gellan on Jun 25, 2021, 11:20

JF vom 25.6.21

AG: Literaturangaben über das Wörterbuchnetz.
Ohne in der Originalvorlage nachzusehen, tun wir uns oft schwer herauszufinden, welche Seiten und Spaltenangaben wir machen sollen.
Immer im Original nachschlagen ist umständlich. Sollen wir bei den Wörterbuchnetz-Zitaten auf ein Online-Zitat ausweichen? vgl. auch Pfeifer.

Die Spaltenangaben sind oft schwer rauszulesen. Man muss sich zwar den davorstehenden und folgenden Artikel raussuchen, damit man die Seitenzahl einschränken kann, aber das ist umständlich. 

Auf lange Sicht wäre es natürlich gut, wenn wir die Zitate auch mit der Quelle verlinken können. Aber vorerst bleiben wir bei diesem Konzept.

Wir setzen uns mal mit den Technikern zusammen, wie wir das umsetzen können.

AG/SW: online-Literatur steht ja im Moment auch in der Literaturliste.
Sollen wir das trennen, damit es 
1. leichter auffindbar wird und 
2. irgendwann auch über eine Auswahlliste ins RT eingefügt werden kann?

Online-Literatur wird über einen anderen Tag eingefügt als die Literatur. Wir schließen uns mal mit den TechnikerInnen zusammen, wie wir das lösen könnten, damit auch die online-Literatur ausgewählt werden kann.

Braucht es da getrennte Literaturlisten?

**Comment by markunz** [comment]
Ist in den Richtlinien aufgeführt.
