### ISSUE TITLE
(Mac-Version) <lbl>-Tags werden in der Vorschau nicht durchgehend angezeigt

### ISSUE THREAD

**Issue by simar0at** [acdh-oeaw/wboe-redaktionstool#157]
In GitLab by @sschoeberl on Jan 20, 2022, 12:06

Mac-Version des RT: obwohl überall <lbl>-Tags gesetzt sind, werden nur manche davon in der Vorschau bzw. im PDF angezeigt:

<img width="1190" alt="Bildschirmfoto_2022-01-20_um_11 59 46" src="https://user-images.githubusercontent.com/114596961/192818054-f1df31f3-8073-4aee-ae24-847eea72381b.png">

<img width="1035" alt="Bildschirmfoto_2022-01-20_um_11 59 32" src="https://user-images.githubusercontent.com/114596961/192818094-7b3a8b97-e058-456e-8f44-0c7abc6e36bb.png">

**Comment by markunz** [comment]
Mac-Version wird nicht weiter unterstützt.
