### ISSUE TITLE
Wechsel in andere Ansichten (Vorschau, XML-Editor) nach ändern der XML nicht mehr möglich (seit Ver. 0.8.0)

### ISSUE THREAD

**Issue by simar0at** [acdh-oeaw/wboe-redaktionstool#161]
In GitLab by @mkunzmann on May 6, 2022, 13:52

Problem tritt bei @patrick.zeitlhuber auf:

Nach einer direkten Bearbeitung einer XML-Datei ist ein Wechsel in andere Ansichten nicht mehr möglich. Erst nach dem Schließen des Redaktionstools lässt sich wieder in andere Ansichten wechseln.
Problem tritt nicht immer auf.

**Comment by markunz** [comment]
Problem tritt  nicht mehr auf.
