### ISSUE TITLE
GitLab-Umstellung - Anpassung an neues Artikel-Repository

### ISSUE THREAD

**Issue by simar0at** [acdh-oeaw/wboe-redaktionstool#166]
In GitLab by @mkunzmann on Sep 8, 2022, 09:13

Am 19.10.2022 erfolgt die Gitlab-Umstellung:

https://gitlab.com/acdh-oeaw → https://gitlab.oeaw.ac.at/

Ist seitens des Redaktionstools hier etwas zu berücksichtigen?

**Comment by markunz** [comment]
Redaktionstool ist auf GitHub öffentlich verfügbar. Der Parser ist ausgelagert.
