### ISSUE TITLE
Zwischenüberschrift(en) bei Lautung ab Buchstaben G entfernen

### ISSUE THREAD

**Issue by Philipp78** [acdh-oeaw/wboe-redaktionstool#175]
Ab der Buchstabenstrecke G/K/Q fällt im Lautungsfeld die Belegauswahl weg, d.h. es gibt nur noch einen Überblick, und die Zwischenüberschriften werden somit überflüssig. 
Es sollte daher ab G/K/Q die Zwischenüberschrift "Überblick" wegfallen: 

![image](https://user-images.githubusercontent.com/9696282/214051896-295410d4-ec0b-4721-98e5-86f57a2fee26.png)

Auf LIÖ werden sogar beide Zwischenüberschriften angezeigt (beide sollten ebenfalls wegfallen), vgl. dazu das entsprechende Issue https://gitlab.oeaw.ac.at/acdh-ch/wboe/lioe-public-frontend/-/issues/261

**Comment by agellan** [comment]
@Philipp78 , @markunz Die Belegauswahl lässt sich aber einfach rauslöschen. inkl. Überschrift.
Darauf könnten wir auch verzichten.
