### ISSUE TITLE
Leerzeichen vor automatischem Komma nach Form Lemma/Variable entfernen

### ISSUE THREAD

**Issue by agellan** [acdh-oeaw/wboe-redaktionstool#187]
vgl. #186

Wenn ich mehrere Form Lemma/Variable-Felder hintereinander schalte, wird automatisch ein Komma dazwischen gesetzt.
Bitte das Leerzeichen vor dem Komma entfernen.

**Beispiel für Leerzeichen** vor dem Komma in der Wortbildung vor einem Form Lemma/Variable 
Artikel *fahren*
[https://gitlab.oeaw.ac.at/acdh-ch/wboe/wboe-artikel/-/blob/master/102_derived_tei/Artikel_Redaktionstool/fahren.xml](url)
![image](https://github.com/acdh-oeaw/wboe-redaktionstool/assets/115615032/40d38a3d-f6a8-4ce3-912a-4529cdfc4bab)
![image](https://github.com/acdh-oeaw/wboe-redaktionstool/assets/115615032/c04dd757-15d3-4f9a-ae95-d572409e3606)

Zum Vergleich:
Bastle ich dasselbe Beispiel nach, schaut aber alles einwandfrei aus. 
Artikel *SPATIUM*
[https://gitlab.oeaw.ac.at/acdh-ch/wboe/wboe-artikel/-/blob/master/102_derived_tei/Artikel_Redaktionstool/SPATIUM.xml
](url)
![image](https://github.com/acdh-oeaw/wboe-redaktionstool/assets/115615032/c46aee83-5c50-4d4c-85a9-9ba55fbc26dc)
Beide Artikel wurden auch mit der Aktuellen 0.8.2 Version gespeichert.

**Comment by hcb79** [comment]
https://gitlab.oeaw.ac.at/acdh-ch/wboe/wboe-artikel/-/blob/master/102_derived_tei/Artikel_Redaktionstool/fahren.xml#L9970
