### ISSUE TITLE
Mitarbeiterin im RT hinzufügen.

### ISSUE THREAD

**Issue by agellan** [acdh-oeaw/wboe-redaktionstool#191]
Dieses Issue ist "important", weil unsere neue Kollegin in 2 Wochen beginnt.

Bitte füge den Namen unserer neuen Mitarbeiterin **Katharina Korecky-Kröll** ein.

An dieser Stelle:
![image](https://github.com/acdh-oeaw/wboe-redaktionstool/assets/115615032/aed05601-a6e6-4ce8-9415-ed47df539735)

Da:
![image](https://github.com/acdh-oeaw/wboe-redaktionstool/assets/115615032/c5833626-5055-45b7-8a79-59725b5faefa)

und letztendlich auch auf LIÖ beim Kürzel. Verwende bitte die Initialen **KK** (3 sind ihr zu verfänglich)
![image](https://github.com/acdh-oeaw/wboe-redaktionstool/assets/115615032/0ba151e7-c02f-40e0-830b-bdc580e89bdc)
Ist der letzte Punkt ein Issue an LIÖ?

**Comment by hcb79** [comment]
Siehe: https://gitlab.oeaw.ac.at/acdh-ch/wboe/wboe-artikel/-/commit/cb7ba6ad8b06a3bcef5c54584155896660ebf332

**Comment by agellan** [comment]
Gleiches Prozedere wie beim letzten Mal: Bitte füge "Wolfgang Koppensteiner" zu den Redakteur:innen hinzu. Es bleibt auf "important" weil er bereits begonnen hat.

**Comment by hcb79** [comment]
Erledigt ... siehe: https://gitlab.oeaw.ac.at/acdh-ch/wboe/wboe-artikel/-/commit/fb61f36352bdac4217f7ed223472146ccee22fa3

**Comment by agellan** [comment]
Hallo Hans Christian,

perfekt, vielen Dank!
Die 8.4er-Version finden wir dann wieder auf GitHub, stimmt's?

LG. Andreas
________________________________
Von: hcb79 ***@***.***>
Gesendet: Dienstag, 5. November 2024 10:36:53
An: acdh-oeaw/wboe-redaktionstool
Cc: Gellan, Andreas; State change
Betreff: [EXT] Re: [acdh-oeaw/wboe-redaktionstool] Mitarbeiterin im RT hinzufügen. (Issue #191)

External Email: please use links and attachments from trusted sources only

Erledigt ... siehe: https://gitlab.oeaw.ac.at/acdh-ch/wboe/wboe-artikel/-/commit/fb61f36352bdac4217f7ed223472146ccee22fa3

**Comment by hcb79** [comment]
> Die 8.4er-Version finden wir dann wieder auf GitHub, stimmt's?

Jain ... es ist im GitLab ... wie sich das mit GitHub synchronisiert weis ich nicht. ;-)
https://gitlab.oeaw.ac.at/acdh-ch/wboe/wboe-artikel
