### ISSUE TITLE
change TEI-structure "Verbreitung"

### ISSUE THREAD

**Issue by simar0at** [acdh-oeaw/wboe-redaktionstool#31]
In GitLab by @LMBreuer on Jan 10, 2020, 12:37

the Redaktionstool has the old tei-structure for "Verbreitung", like:

```
         <usg type="geo">
          <placeName type="bundesland" ref="/geodata-wboe.xml#p1A">STir.</placeName>
        </usg>
        <usg type="geo">
          <placeName type="bundesland" ref="/geodata-wboe.xml#p1B">OTir.</placeName>
        </usg>
        <usg type="geo">
          <placeName type="bundesland" ref="/geodata-wboe.xml#p1C">NTir.</placeName>
        </usg>
        <usg type="geo">
          <placeName type="bundesland" ref="/geodata-wboe.xml#p2">Ktn.</placeName>
        </usg>
        <usg type="geo">
          <placeName type="bundesland" ref="/geodata-wboe.xml#p3">Stmk.</placeName>
        </usg>
```

should be following:

>                     <usg type="verbreitung">
>                         <placeName type="grossregion">mSTir.</placeName>
>                         <placeName type="grossregion">öSTir.</placeName>
>                         <placeName type="grossregion">OTir.</placeName>
>                         <placeName type="grossregion">NTir.</placeName>
>                         <placeName type="grossregion">Ktn.</placeName>
>                         <placeName type="grossregion">Stmk.</placeName>
>                         <placeName type="grossregion">Pinzg.</placeName>
>                         <placeName type="grossregion">OÖ</placeName>
>                         <placeName type="grossregion">NÖ</placeName>
>                         <placeName type="grossregion">Bgl.</placeName>
>                     </usg>

**Comment by markunz** [comment]
TEI structure works in rendering of articles.

![image](https://user-images.githubusercontent.com/114596961/214614521-87edada2-b0c7-444e-865d-e8cbb4b55081.png)

```
<usg type="geo">
  <placeName type="bundesland" ref="/geodata-wboe.xml#p1A">STir.</placeName>
</usg>
<usg type="geo">
  <placeName type="bundesland" ref="/geodata-wboe.xml#p1B">OTir.</placeName>
</usg>
<usg type="geo">
  <placeName type="bundesland" ref="/geodata-wboe.xml#p1C">NTir.</placeName>
</usg>
```
